version: "3.8"

services:
  account:
    image: shympyo.kr.ncr.ntruss.com/account-service
    container_name: account-service
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      # 관리(Actuator) & CORS
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
      APP_CORS_ALLOWED_ORIGINS: "http://localhost:3000,https://your-domain.com"

      # DB 설정
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      # Kakao OAuth2
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_TOKEN_URI: ${KAKAO_TOKEN_URI}
      KAKAO_USER_INFO_URI: ${KAKAO_USER_INFO_URI}

      # Naver OAuth2
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_REDIRECT_URI: ${NAVER_REDIRECT_URI}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      NAVER_TOKEN_URI: ${NAVER_TOKEN_URI}
      NAVER_USER_INFO_URI: ${NAVER_USER_INFO_URI}

      # Google OAuth2
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_TOKEN_URI: ${GOOGLE_TOKEN_URI}
      GOOGLE_USER_INFO_URI: ${GOOGLE_USER_INFO_URI}

    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
