apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patches.yaml
images:
  - name: shympyo.kr.ncr.ntruss.com/shympyo-backend
    newTag: dev-0.0.1   # SourceBuild 빌드번호로 대체 예정